# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-13 03:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='medicamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_medicamento', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=20)),
                ('precio13', models.FloatField(max_length=20)),
                ('precio14', models.FloatField(max_length=20)),
                ('precio15', models.FloatField(max_length=20)),
            ],
        ),
    ]
