# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-13 03:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedicamentosApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='farmacia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_farmacia', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=20)),
                ('descuento', models.FloatField(max_length=20)),
            ],
        ),
    ]
